repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
    - id: insert-license
      files: \.py$
      args:
        - --license-filepath
        - ./license_header.txt
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
-   repo: local
    hooks:
    - id: docmd
      name: docmd
      language: system
      entry: bash -c "make docs"
      files: .

