language: python
cache: 
  pip: True

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

sudo: false

jobs:
    include:
    - name: test
      stage: test
      script:
        - ./ci-test.sh

after_success:
    - ./ci-cov.sh

branches:
    only:
    - master
    - /^v/

services:
    - mysql
